from __future__ import annotations

NETWORK_ATTRIBUTES = [
    "event_time_epoch",
    "event_time_iso",
    "src_ip",
    "dst_ip",
    "src_port",
    "dst_port",
    "local_address",
    "local_port",
    "remote_address",
    "remote_port",
    "protocol_name",
    "protocol_number",
    "network_direction",
    "flow_duration",
    "duration",
    "rate",
    "srate",
    "drate",
    "header_length",
    "total_size",
    "total_sum",
    "packet_number",
    "iat",
    "tcp_fin",
    "tcp_syn",
    "tcp_rst",
    "tcp_psh",
    "tcp_ack",
    "tcp_urg",
    "tcp_ece",
    "tcp_cwr",
    "ack_count",
    "syn_count",
    "fin_count",
    "urg_count",
    "rst_count",
    "protocol_http",
    "protocol_https",
    "protocol_dns",
    "protocol_tcp",
    "protocol_udp",
    "protocol_icmp",
    "label",
    "sub_label",
    "sub_label_cat",
]

SYSTEM_ATTRIBUTES = [
    "event_time_epoch",
    "event_time_iso",
    "source",
    "entity_id",
    "entity_type",
    "source_entity_id",
    "target_entity_id",
    "process_pid",
    "process_ppid",
    "process_tgid",
    "process_name",
    "process_exe",
    "process_command_line",
    "user_uid",
    "user_euid",
    "group_gid",
    "group_egid",
    "file_path",
    "file_subtype",
    "file_permissions",
    "file_mode",
]

CROSS_ATTRIBUTES = [
    "event_time_epoch",
    "event_time_iso",
    "src_ip",
    "dst_ip",
    "src_port",
    "dst_port",
    "network_direction",
    "flow_duration",
    "total_size",
    "process_pid",
    "process_ppid",
    "process_name",
    "process_exe",
    "process_command_line",
]

LLM_ATTRIBUTES = [
    "event_time_epoch",
    "event_time_iso",
    "llm_provider",
    "llm_model",
    "llm_prompt",
    "llm_response",
    "llm_tool_name",
    "llm_tool_input",
    "llm_tool_output",
    "prompt",
    "response",
    "tool_name",
    "tool_input",
    "tool_output",
    "session_id",
    "user_uid",
]

IDENTITY_ATTRIBUTES = [
    "event_time_epoch",
    "event_time_iso",
    "user_uid",
    "user_euid",
    "group_gid",
    "group_egid",
    "source_entity_id",
    "target_entity_id",
    "identity",
    "principal",
    "account_name",
    "login_result",
    "auth_method",
    "session_id",
    "src_ip",
    "dst_ip",
]

CLOUD_ATTRIBUTES = [
    "event_time_epoch",
    "event_time_iso",
    "cloud_provider",
    "cloud_account",
    "cloud_region",
    "cloud_service",
    "cloud_action",
    "cloud_resource",
    "cloud_identity",
    "source",
    "entity_id",
    "user_uid",
    "src_ip",
    "dst_ip",
]

CROSS_CATEGORY_TOKENS = [
    "cross:sensitive_file_read_AND_large_upload_same_host_15m",
    "cross:encoded_command_AND_first_seen_domain_same_host_15m",
    "cross:llm_file_read_tool_AND_system_sensitive_file_read_same_user_15m",
    "cross:failed_login_burst_AND_successful_login_same_user_15m",
    "cross:secret_read_tool_AND_external_post_same_user_15m",
]

SUBCATEGORY_SCHEMAS = {
    "network": NETWORK_ATTRIBUTES,
    "system": SYSTEM_ATTRIBUTES,
    "llm": LLM_ATTRIBUTES,
    "identity": IDENTITY_ATTRIBUTES,
    "cloud": CLOUD_ATTRIBUTES,
    "cross": CROSS_ATTRIBUTES,
}

SUBCATEGORY_NAMES = ["system", "network", "llm", "identity", "cloud", "cross"]

# Backward-compatible aliases for older tests/imports.
INTER_CATEGORY_ATTRIBUTES = CROSS_ATTRIBUTES
SPECIALIZED_MODEL_SCHEMAS = SUBCATEGORY_SCHEMAS
SPECIALIZED_MODEL_NAMES = ["network", "system", "cross"]
