from __future__ import annotations

NO_APPLICABLE_POLICY = "NO_APPLICABLE_POLICY"
UNKNOWN_CATEGORY = "UNKNOWN_CATEGORY"
MALFORMED_ROW = "MALFORMED_ROW"
CONFLICTING_FIELD_VALUES = "CONFLICTING_FIELD_VALUES"
MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"
INVALID_TIMESTAMP = "INVALID_TIMESTAMP"
OUTSIDE_AUTHORIZED_TIME = "OUTSIDE_AUTHORIZED_TIME"
UNAUTHORIZED_HOST = "UNAUTHORIZED_HOST"
UNAUTHORIZED_LOCAL_IP = "UNAUTHORIZED_LOCAL_IP"
UNAUTHORIZED_USER = "UNAUTHORIZED_USER"
UNAUTHORIZED_PROGRAM = "UNAUTHORIZED_PROGRAM"
UNAUTHORIZED_PROGRAM_PATH = "UNAUTHORIZED_PROGRAM_PATH"
UNAUTHORIZED_PARENT_PROGRAM = "UNAUTHORIZED_PARENT_PROGRAM"
COMMAND_LINE_POLICY_VIOLATION = "COMMAND_LINE_POLICY_VIOLATION"
UNKNOWN_NETWORK_DIRECTION = "UNKNOWN_NETWORK_DIRECTION"
UNAUTHORIZED_REMOTE_IP = "UNAUTHORIZED_REMOTE_IP"
UNAUTHORIZED_REMOTE_DOMAIN = "UNAUTHORIZED_REMOTE_DOMAIN"
UNAUTHORIZED_PROTOCOL = "UNAUTHORIZED_PROTOCOL"
UNAUTHORIZED_PORT = "UNAUTHORIZED_PORT"
NETWORK_POLICY_MISMATCH = "NETWORK_POLICY_MISMATCH"
SYSTEM_POLICY_MISMATCH = "SYSTEM_POLICY_MISMATCH"
INTERNAL_FILTER_ERROR = "INTERNAL_FILTER_ERROR"
EVENT_ID_ALWAYS_FORWARD = "EVENT_ID_ALWAYS_FORWARD"
EVENT_ID_SUPPRESS_MATCH = "EVENT_ID_SUPPRESS_MATCH"
EVENT_ID_MISSING = "EVENT_ID_MISSING"
EVENT_ID_MALFORMED = "EVENT_ID_MALFORMED"
EVENT_ID_NEUTRAL = "EVENT_ID_NEUTRAL"
SEVERITY_ALWAYS_FORWARD = "SEVERITY_ALWAYS_FORWARD"
SEVERITY_SUPPRESS_MATCH = "SEVERITY_SUPPRESS_MATCH"
SEVERITY_MISSING = "SEVERITY_MISSING"
SEVERITY_MALFORMED = "SEVERITY_MALFORMED"
SEVERITY_NEUTRAL = "SEVERITY_NEUTRAL"
AGGREGATION_TIMESTAMP_INVALID = "AGGREGATION_TIMESTAMP_INVALID"
AGGREGATION_TIMESTAMP_CONFLICT = "AGGREGATION_TIMESTAMP_CONFLICT"
AGGREGATION_OUT_OF_ORDER_TIMESTAMP = "AGGREGATION_OUT_OF_ORDER_TIMESTAMP"

ALL_REASON_CODES = {
    NO_APPLICABLE_POLICY,
    UNKNOWN_CATEGORY,
    MALFORMED_ROW,
    CONFLICTING_FIELD_VALUES,
    MISSING_REQUIRED_FIELD,
    INVALID_TIMESTAMP,
    OUTSIDE_AUTHORIZED_TIME,
    UNAUTHORIZED_HOST,
    UNAUTHORIZED_LOCAL_IP,
    UNAUTHORIZED_USER,
    UNAUTHORIZED_PROGRAM,
    UNAUTHORIZED_PROGRAM_PATH,
    UNAUTHORIZED_PARENT_PROGRAM,
    COMMAND_LINE_POLICY_VIOLATION,
    UNKNOWN_NETWORK_DIRECTION,
    UNAUTHORIZED_REMOTE_IP,
    UNAUTHORIZED_REMOTE_DOMAIN,
    UNAUTHORIZED_PROTOCOL,
    UNAUTHORIZED_PORT,
    NETWORK_POLICY_MISMATCH,
    SYSTEM_POLICY_MISMATCH,
    INTERNAL_FILTER_ERROR,
    EVENT_ID_ALWAYS_FORWARD,
    EVENT_ID_SUPPRESS_MATCH,
    EVENT_ID_MISSING,
    EVENT_ID_MALFORMED,
    EVENT_ID_NEUTRAL,
    SEVERITY_ALWAYS_FORWARD,
    SEVERITY_SUPPRESS_MATCH,
    SEVERITY_MISSING,
    SEVERITY_MALFORMED,
    SEVERITY_NEUTRAL,
    AGGREGATION_TIMESTAMP_INVALID,
    AGGREGATION_TIMESTAMP_CONFLICT,
    AGGREGATION_OUT_OF_ORDER_TIMESTAMP,
}
